* Flood Watch - Dynamic Flood Risk Information Suite
  Flood watch is a tool which aims to provide up-to-date information
  concerning flooding hazard to the general public.  It takes in a
  diverse source of data, including terrain relief, river height
  sensor, and historic flood risks, and congregates these sources into
  a single flood danger metric which is then overlayed onto the map.
  The purpose of this tool is to provide any interested party with the
  information to make decisions in the event of an emergency.

  This repository contains both the front-end android application,
  located in the ~android-dev~ folder, and the backend tools for
  analysis, which includes webcrawler inside the ~StationDataCrawler~
  folder, and the image analysis tools inside the
  ~AnalysisBackend.zip~ file. Some preliminary results are provided
  in the ~PhotoResultsSubmission~ folder.
** Usage
*** Android-dev
    The source code for the Android application is located in this
    folder. It can be built using the usual tools, and details are
    provided in a separate readme. Some screencaps of the application
    are also provided inside the folder. Eventually, the purposeof
    the app would be to fetch our calculated flood risk metric
    as a contour map for the user's geographical location.
*** Station Data Crawler
    This is a set of Python tools which obtains the list of height
    sensors for in rivers in queensland, and proceeds down the list,
    fetching the most recent readings from these sensors and storing
    the results in a ~csv~ file. Further usage details are located
    inside the ~read_me~ file in the folder.
*** Analysis Backend
    This is the main tool used to analyse information from the
    separate sources and provide the output for the Android
    application. Right now it exists as several functions which
    must be chained together by hand, but eventually the process
    will be entirely automated.
